[package]
name = "joseph/jokers-realm"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Cmdr = "evaera/cmdr@1.12.0"
Trove = "sleitnick/trove@1.5.1"
Observers = "sleitnick/observers@0.3.4"
T = "osyrisrblx/t@3.1.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"